import spacy
import re
from spacy.matcher import PhraseMatcher
import json
import os

nlp = spacy.load("en_core_web_sm")


BASE_DIR = os.path.dirname(__file__)
skills_file = os.path.join(BASE_DIR, "skills.json")

with open(skills_file, "r") as f:
    SKILLS_DB = json.load(f)

def normalize_text(text):
    text = text.lower()

    # Standardize separators
    text = re.sub(r"[|•·]", " ", text)
    text = re.sub(r"[()/]", " ", text)

    # replacements = {
    #     r"\bnodejs\b": "node.js",
    #     r"\bnode js\b": "node.js",
    #     r"\bci cd\b": "ci/cd",
    #     r"\bci-cd\b": "ci/cd",
    #     r"\bpostgres\b": "postgresql",
    #     r"\bjs\b": "javascript",
    #     r"\bts\b": "typescript",
    #     r"\bpy\b": "python",
    #     r"\breactjs\b": "react",
    #     r"\bnextjs\b": "next.js",
    #     r"\bvuejs\b": "vue",
    #     r"\basp net\b": "asp.net",
    #     r"\bdot net\b": ".net",
    #     r"\bgcp\b": "google cloud platform",
    #     r"\baws cloud\b": "aws",
    #     r"\bml\b": "machine learning",
    #     r"\bdl\b": "deep learning",
    #     r"\bnlp\b": "natural language processing",
    #     r"\bai\b": "artificial intelligence",
    #     r"\brestful\b": "rest api",
    #     r"\brest api\b": "rest api",
    #     r"\boops\b": "oop",
    #     r"\bobject oriented programming\b": "oop"
    # }


    replacements = {
            r"\bnodejs\b": "node.js",
            r"\bnode js\b": "node.js",
            r"\bci cd\b": "ci/cd",
            r"\bci-cd\b": "ci/cd",
            r"\bpostgres\b": "postgresql",
            r"\bjs\b": "javascript",
            r"\bts\b": "typescript",
            r"\bpy\b": "python",
            r"\breactjs\b": "react",
            r"\bnextjs\b": "next.js",
            r"\bvuejs\b": "vue",
            r"\basp net\b": "asp.net",
            r"\bdot net\b": ".net",
            r"\bgcp\b": "google cloud platform",
            r"\baws cloud\b": "aws",
            r"\bml\b": "machine learning",
            r"\bdl\b": "deep learning",
            r"\bnlp\b": "natural language processing",
            r"\bai\b": "artificial intelligence",
            r"\brestful\b": "rest api",
            r"\brest api\b": "rest api",
            r"\boops\b": "oop",
            r"\bobject oriented programming\b": "oop",
            r"\bdev ops\b": "devops",
            r"\bk8s\b": "kubernetes",
            r"\bk8\b": "kubernetes",
            r"\bterraform\b": "terraform",
            r"\bansible\b": "ansible",
            r"\bjenkins\b": "jenkins",
            r"\bdocker\b": "docker",
            r"\bgraph ql\b": "graphql",
            r"\bwasm\b": "webassembly",
            r"\bweb assembly\b": "webassembly",
            r"\bcrna\b": "certified registered nurse anesthetist",
            r"\bcrnp\b": "certified registered nurse practitioner",
            r"\brn\b": "registered nurse",
            r"\blpn\b": "licensed practical nurse",
            r"\blvn\b": "licensed vocational nurse",
            r"\bcna\b": "certified nursing assistant",
            r"\bcma\b": "certified medical assistant",
            r"\bemt\b": "emergency medical technician",
            r"\bparamedic\b": "paramedic",
            r"\bcpr\b": "cardiopulmonary resuscitation",
            r"\bacls\b": "advanced cardiac life support",
            r"\bbcls\b": "basic cardiac life support",
            r"\bpals\b": "pediatric advanced life support",
            r"\bnrp\b": "neonatal resuscitation program",
            r"\behr\b": "electronic health records",
            r"\bemr\b": "electronic medical records",
            r"\bhipaa\b": "health insurance portability and accountability act",
            r"\becg\b": "electrocardiogram",
            r"\beeg\b": "electroencephalogram",
            r"\bmri\b": "magnetic resonance imaging",
            r"\bct scan\b": "computed tomography scan",
            r"\bpet scan\b": "positron emission tomography scan",
            r"\busg\b": "ultrasonography",
            r"\biv\b": "intravenous",
            r"\bim\b": "intramuscular",
            r"\bpo\b": "oral administration",
            r"\bprn\b": "as needed",
            r"\bbid\b": "twice daily",
            r"\btid\b": "three times daily",
            r"\bqid\b": "four times daily",
            r"\bqhs\b": "every night",
            r"\bac\b": "before meals",
            r"\bpc\b": "after meals",
            r"\bstat\b": "immediately",
            r"\bcbc\b": "complete blood count",
            r"\bbmp\b": "basic metabolic panel",
            r"\bcmp\b": "comprehensive metabolic panel",
            r"\blft\b": "liver function test",
            r"\brft\b": "renal function test",
            r"\btsh\b": "thyroid stimulating hormone",
            r"\ba1c\b": "hemoglobin a1c",
            r"\bpt\b": "prothrombin time",
            r"\bptt\b": "partial thromboplastin time",
            r"\binr\b": "international normalized ratio",
            r"\burinalysis\b": "urinalysis",
            r"\bgmp\b": "good manufacturing practices",
            r"\bglp\b": "good laboratory practices",
            r"\bgcp\b": "good clinical practices",
            r"\bgdp\b": "good documentation practices",
            r"\bqbd\b": "quality by design",
            r"\bapi\b": "active pharmaceutical ingredient",
            r"\bndc\b": "national drug code",
            r"\banda\b": "abbreviated new drug application",
            r"\bnda\b": "new drug application",
            r"\bind\b": "investigational new drug",
            r"\bbla\b": "biologics license application",
            r"\bpk\b": "pharmacokinetics",
            r"\bpd\b": "pharmacodynamics",
            r"\badme\b": "absorption distribution metabolism excretion",
            r"\bic50\b": "half maximal inhibitory concentration",
            r"\bec50\b": "half maximal effective concentration",
            r"\bld50\b": "median lethal dose",
            r"\bted50\b": "median effective dose",
            r"\btd50\b": "median toxic dose",
            r"\bpcr\b": "polymerase chain reaction",
            r"\bqpcr\b": "quantitative polymerase chain reaction",
            r"\brt-pcr\b": "reverse transcription polymerase chain reaction",
            r"\belisa\b": "enzyme-linked immunosorbent assay",
            r"\bwestern blot\b": "western blot",
            r"\bnorthern blot\b": "northern blot",
            r"\bsouthern blot\b": "southern blot",
            r"\bhplc\b": "high-performance liquid chromatography",
            r"\bgc\b": "gas chromatography",
            r"\bms\b": "mass spectrometry",
            r"\bgc-ms\b": "gas chromatography-mass spectrometry",
            r"\blc-ms\b": "liquid chromatography-mass spectrometry",
            r"\bnmr\b": "nuclear magnetic resonance",
            r"\bxrd\b": "x-ray diffraction",
            r"\bftir\b": "fourier-transform infrared spectroscopy",
            r"\buv-vis\b": "ultraviolet-visible spectroscopy",
            r"\bdsd\b": "dissolution",
            r"\bdisintegration\b": "disintegration testing",
            r"\bcad\b": "computer-aided design",
            r"\bcam\b": "computer-aided manufacturing",
            r"\bcae\b": "computer-aided engineering",
            r"\bfea\b": "finite element analysis",
            r"\bcfd\b": "computational fluid dynamics",
            r"\bcim\b": "computer-integrated manufacturing",
            r"\bcnc\b": "computer numerical control",
            r"\bplc\b": "programmable logic controller",
            r"\bdcs\b": "distributed control system",
            r"\bscada\b": "supervisory control and data acquisition",
            r"\bhmi\b": "human-machine interface",
            r"\bpid\b": "proportional-integral-derivative",
            r"\bpcb\b": "printed circuit board",
            r"\bvlsi\b": "very-large-scale integration",
            r"\basic\b": "application-specific integrated circuit",
            r"\bfpga\b": "field-programmable gate array",
            r"\bdsp\b": "digital signal processor",
            r"\bmems\b": "micro-electromechanical systems",
            r"\bic engine\b": "internal combustion engine",
            r"\bhvac\b": "heating ventilation and air conditioning",
            r"\bhvacr\b": "heating ventilation air conditioning and refrigeration",
            r"\bplumbing\b": "plumbing",
            r"\belv\b": "electrical",
            r"\bems\b": "energy management system",
            r"\bbms\b": "building management system",
            r"\bbim\b": "building information modeling",
            r"\bpmis\b": "project management information system",
            r"\bcpm\b": "critical path method",
            r"\bpert\b": "program evaluation and review technique",
            r"\beot\b": "earned value management",
            r"\brfi\b": "request for information",
            r"\brfp\b": "request for proposal",
            r"\brfq\b": "request for quotation",
            r"\bifb\b": "invitation for bid",
            r"\bifc\b": "issued for construction",
            r"\bifd\b": "issued for design",
            r"\brcd\b": "reinforced concrete design",
            r"\bsteel design\b": "structural steel design",
            r"\bsoil testing\b": "geotechnical testing",
            r"\bcompaction\b": "soil compaction",
            r"\bbackfill\b": "backfilling",
            r"\bgrading\b": "site grading",
            r"\blast\b": "lot and block",
            r"\bmetes and bounds\b": "metes and bounds",
            r"\bplss\b": "public land survey system",
            r"\bsix sigma\b": "six sigma",
            r"\bdmaic\b": "define measure analyze improve control",
            r"\bdmadv\b": "define measure analyze design verify",
            r"\bspc\b": "statistical process control",
            r"\bsqc\b": "statistical quality control",
            r"\btqm\b": "total quality management",
            r"\btpm\b": "total productive maintenance",
            r"\boee\b": "overall equipment effectiveness",
            r"\bmttr\b": "mean time to repair",
            r"\bmtbf\b": "mean time between failures",
            r"\bsmed\b": "single-minute exchange of die",
            r"\bvsm\b": "value stream mapping",
            r"\bkaizen\b": "kaizen",
            r"\bpoka-yoke\b": "poka-yoke",
            r"\bkanban\b": "kanban",
            r"\bjit\b": "just-in-time",
            r"\bandon\b": "andon",
            r"\bheijunka\b": "production smoothing",
            r"\bgemba\b": "gemba",
            r"\bhoshin kanri\b": "hoshin kanri",
            r"\bpdca\b": "plan-do-check-act",
            r"\bcap-d-o\b": "check-act-plan-do",
            r"\biso\b": "international organization for standardization",
            r"\biso 9001\b": "iso 9001 quality management",
            r"\biso 14001\b": "iso 14001 environmental management",
            r"\biso 45001\b": "iso 45001 occupational health and safety",
            r"\bohsas\b": "occupational health and safety assessment series",
            r"\bscm\b": "supply chain management",
            r"\b3pl\b": "third-party logistics",
            r"\b4pl\b": "fourth-party logistics",
            r"\bwms\b": "warehouse management system",
            r"\btms\b": "transportation management system",
            r"\byms\b": "yard management system",
            r"\blms\b": "labor management system",
            r"\bgps\b": "global positioning system",
            r"\brfid\b": "radio-frequency identification",
            r"\beoq\b": "economic order quantity",
            r"\brop\b": "reorder point",
            r"\bvmi\b": "vendor-managed inventory",
            r"\bcmi\b": "co-managed inventory",
            r"\bcpfr\b": "collaborative planning forecasting and replenishment",
            r"\bdrp\b": "distribution requirements planning",
            r"\bmrp\b": "material requirements planning",
            r"\bmrp ii\b": "manufacturing resource planning",
            r"\berp\b": "enterprise resource planning",
            r"\bftl\b": "full truckload",
            r"\bltl\b": "less than truckload",
            r"\bfcl\b": "full container load",
            r"\blcl\b": "less than container load",
            r"\bincoterms\b": "international commercial terms",
            r"\bfob\b": "free on board",
            r"\bcif\b": "cost insurance freight",
            r"\bexw\b": "ex works",
            r"\bdap\b": "delivered at place",
            r"\bddu\b": "delivered duty unpaid",
            r"\bddd\b": "delivered duty paid",
            r"\broi\b": "return on investment",
            r"\bros\b": "return on sales",
            r"\broa\b": "return on assets",
            r"\broe\b": "return on equity",
            r"\broce\b": "return on capital employed",
            r"\birr\b": "internal rate of return",
            r"\bnpv\b": "net present value",
            r"\bpv\b": "present value",
            r"\bfv\b": "future value",
            r"\bwacc\b": "weighted average cost of capital",
            r"\bebit\b": "earnings before interest and taxes",
            r"\bebitda\b": "earnings before interest taxes depreciation and amortization",
            r"\bgp\b": "gross profit",
            r"\bnpat\b": "net profit after tax",
            r"\bcogs\b": "cost of goods sold",
            r"\bsga\b": "selling general and administrative",
            r"\br&d\b": "research and development",
            r"\bcapex\b": "capital expenditure",
            r"\bopex\b": "operating expenditure",
            r"\bgaap\b": "generally accepted accounting principles",
            r"\bifrs\b": "international financial reporting standards",
            r"\bsox\b": "sarbanes-oxley act",
            r"\bap\b": "accounts payable",
            r"\bar\b": "accounts receivable",
            r"\bgl\b": "general ledger",
            r"\bpl\b": "profit and loss",
            r"\bbc\b": "balance sheet",
            r"\bcf\b": "cash flow",
            r"\bocf\b": "operating cash flow",
            r"\bfcf\b": "free cash flow",
            r"\bseo\b": "search engine optimization",
            r"\bsem\b": "search engine marketing",
            r"\bppc\b": "pay-per-click",
            r"\bcpc\b": "cost per click",
            r"\bcpm\b": "cost per mille",
            r"\bcpa\b": "cost per acquisition",
            r"\bctr\b": "click-through rate",
            r"\bcvr\b": "conversion rate",
            r"\broas\b": "return on ad spend",
            r"\bcta\b": "call to action",
            r"\bua\b": "user acquisition",
            r"\bcac\b": "customer acquisition cost",
            r"\bltv\b": "lifetime value",
            r"\bnps\b": "net promoter score",
            r"\bcsat\b": "customer satisfaction score",
            r"\bce\b": "customer effort score",
            r"\bcr\b": "conversion rate",
            r"\bb2b\b": "business-to-business",
            r"\bb2c\b": "business-to-consumer",
            r"\bc2c\b": "consumer-to-consumer",
            r"\bcrm\b": "customer relationship management",
            r"\bmarketing automation\b": "marketing automation",
            r"\binbound marketing\b": "inbound marketing",
            r"\boutbound marketing\b": "outbound marketing",
            r"\bcontent marketing\b": "content marketing",
            r"\bgrowth hacking\b": "growth hacking",
            r"\bplg\b": "product-led growth",
            r"\bslg\b": "sales-led growth",
            r"\bmlg\b": "marketing-led growth",
            r"\bhr\b": "human resources",
            r"\bhrbp\b": "human resources business partner",
            r"\bshrm\b": "society for human resource management",
            r"\bhrci\b": "human resource certification institute",
            r"\bphr\b": "professional in human resources",
            r"\bsphr\b": "senior professional in human resources",
            r"\bgphr\b": "global professional in human resources",
            r"\bcphr\b": "certified professional in human resources",
            r"\bshrm-cp\b": "shrm certified professional",
            r"\bshrm-scp\b": "shrm senior certified professional",
            r"\bhrms\b": "human resources management system",
            r"\bhris\b": "human resources information system",
            r"\bhcm\b": "human capital management",
            r"\bpayroll\b": "payroll",
            r"\bcomp & ben\b": "compensation and benefits",
            r"\bt&d\b": "training and development",
            r"\bl&d\b": "learning and development",
            r"\bod\b": "organizational development",
            r"\btm\b": "talent management",
            r"\bta\b": "talent acquisition",
            r"\brecruiting\b": "recruiting",
            r"\bonboarding\b": "onboarding",
            r"\boffboarding\b": "offboarding",
            r"\bperformance mgmt\b": "performance management",
            r"\bkpis\b": "key performance indicators",
            r"\bokrs\b": "objectives and key results",
            r"\b360 feedback\b": "360-degree feedback",
            r"\bees\b": "employee engagement survey",
            r"\beo\b": "employee orientation",
            r"\bhr analytics\b": "hr analytics",
            r"\bpeople analytics\b": "people analytics",
            r"\bworkforce planning\b": "workforce planning",
            r"\besq\b": "esquire",
            r"\bjd\b": "juris doctor",
            r"\bllm\b": "master of laws",
            r"\bllb\b": "bachelor of laws",
            r"\bplc\b": "public limited company",
            r"\bltd\b": "limited",
            r"\binc\b": "incorporated",
            r"\bcorp\b": "corporation",
            r"\bllc\b": "limited liability company",
            r"\bllp\b": "limited liability partnership",
            r"\bipa\b": "intellectual property",
            r"\bip\b": "intellectual property",
            r"\btm\b": "trademark",
            r"\bsm\b": "service mark",
            r"\bcopyright\b": "copyright",
            r"\bpatent\b": "patent",
            r"\butility patent\b": "utility patent",
            r"\bdesign patent\b": "design patent",
            r"\bplant patent\b": "plant patent",
            r"\bnda\b": "non-disclosure agreement",
            r"\bmoa\b": "memorandum of agreement",
            r"\bmou\b": "memorandum of understanding",
            r"\bsow\b": "statement of work",
            r"\bsla\b": "service level agreement",
            r"\bola\b": "operating level agreement",
            r"\buca\b": "underpinning contract",
            r"\bmsa\b": "master service agreement",
            r"\beula\b": "end user license agreement",
            r"\btos\b": "terms of service",
            r"\bprivacy policy\b": "privacy policy",
            r"\bcookie policy\b": "cookie policy",
            r"\barbitration\b": "arbitration",
            r"\bmediation\b": "mediation",
            r"\bconciliation\b": "conciliation",
            r"\badr\b": "alternative dispute resolution",
            r"\bk-12\b": "kindergarten through 12th grade",
            r"\bk-5\b": "kindergarten through 5th grade",
            r"\b6-8\b": "6th through 8th grade",
            r"\b9-12\b": "9th through 12th grade",
            r"\bearly childhood\b": "early childhood education",
            r"\bece\b": "early childhood education",
            r"\besl\b": "english as a second language",
            r"\btefl\b": "teaching english as a foreign language",
            r"\btesol\b": "teaching english to speakers of other languages",
            r"\bcelta\b": "certificate in english language teaching to adults",
            r"\bdelta\b": "diploma in english language teaching to adults",
            r"\bielts\b": "international english language testing system",
            r"\btoefl\b": "test of english as a foreign language",
            r"\btoeic\b": "test of english for international communication",
            r"\bgpa\b": "grade point average",
            r"\bcurriculum\b": "curriculum",
            r"\bpedagogy\b": "pedagogy",
            r"\bandragogy\b": "andragogy",
            r"\bheutagogy\b": "heutagogy",
            r"\bbloom's taxonomy\b": "bloom's taxonomy",
            r"\bformative assessment\b": "formative assessment",
            r"\bsummative assessment\b": "summative assessment",
            r"\bdiagnostic assessment\b": "diagnostic assessment",
            r"\bauthentic assessment\b": "authentic assessment",
            r"\bportfolio assessment\b": "portfolio assessment",
            r"\brubric\b": "rubric",
            r"\bstandards-based grading\b": "standards-based grading",
            r"\bcompetency-based education\b": "competency-based education",
            r"\bmastery learning\b": "mastery learning",
            r"\bflipped classroom\b": "flipped classroom",
            r"\bblended learning\b": "blended learning",
            r"\bhybrid learning\b": "hybrid learning",
            r"\bsynchronous learning\b": "synchronous learning",
            r"\basynchronous learning\b": "asynchronous learning",
            r"\blms\b": "learning management system",
            r"\blxp\b": "learning experience platform",
            r"\bscorm\b": "sharable content object reference model",
            r"\bxapi\b": "experience api",
            r"\bcmc\b": "course management system",
            r"\bf&b\b": "food and beverage",
            r"\bfto\b": "front office",
            r"\bhousekeeping\b": "housekeeping",
            r"\bhskt\b": "housekeeping",
            r"\bste\b": "stewarding",
            r"\bengineering maintenance\b": "engineering and maintenance",
            r"\bsecurity safety\b": "security and safety",
            r"\bsales marketing\b": "sales and marketing",
            r"\bhaccp\b": "hazard analysis critical control point",
            r"\bpos\b": "point of sale",
            r"\bpms\b": "property management system",
            r"\bcrs\b": "central reservation system",
            r"\bgds\b": "global distribution system",
            r"\bota\b": "online travel agency",
            r"\brevpar\b": "revenue per available room",
            r"\badr\b": "average daily rate",
            r"\bocc%\b": "occupancy percentage",
            r"\bgop\b": "gross operating profit",
            r"\bnop\b": "net operating profit",
            r"\bebitda hospitality\b": "earnings before interest taxes depreciation amortization",
            r"\bbistro\b": "bistro",
            r"\bbuffet\b": "buffet",
            r"\ba la carte\b": "a la carte",
            r"\btable d'hote\b": "table d'hote",
            r"\bprix fixe\b": "prix fixe",
            r"\bamuse-bouche\b": "amuse-bouche",
            r"\bhors d'oeuvre\b": "hors d'oeuvre",
            r"\bcanape\b": "canape",
            r"\bentree\b": "entree",
            r"\bmain course\b": "main course",
            r"\bdessert\b": "dessert",
            r"\bmise en place\b": "mise en place",
            r"\bbrigade system\b": "kitchen brigade system",
            r"\bcmyk\b": "cyan magenta yellow black",
            r"\brgb\b": "red green blue",
            r"\bhex\b": "hexadecimal",
            r"\bpantone\b": "pantone matching system",
            r"\bppi\b": "pixels per inch",
            r"\bdpi\b": "dots per inch",
            r"\blpi\b": "lines per inch",
            r"\bvector graphics\b": "vector graphics",
            r"\braster graphics\b": "raster graphics",
            r"\bbitmap\b": "bitmap",
            r"\bsvg\b": "scalable vector graphics",
            r"\bePS\b": "encapsulated postscript",
            r"\bai\b": "adobe illustrator",
            r"\bpsd\b": "photoshop document",
            r"\bindd\b": "indesign document",
            r"\baep\b": "after effects project",
            r"\bprproj\b": "premiere pro project",
            r"\btypography\b": "typography",
            r"\bserif\b": "serif",
            r"\bsans serif\b": "sans serif",
            r"\bscript font\b": "script font",
            r"\bdisplay font\b": "display font",
            r"\bkerning\b": "kerning",
            r"\btracking\b": "tracking",
            r"\bleading\b": "leading",
            r"\bx-height\b": "x-height",
            r"\bcounter\b": "counter",
            r"\bascender\b": "ascender",
            r"\bdescender\b": "descender",
            r"\bphotography\b": "photography",
            r"\baperture\b": "aperture",
            r"\bshutter speed\b": "shutter speed",
            r"\biso\b": "iso",
            r"\bexposure\b": "exposure",
            r"\bwhite balance\b": "white balance",
            r"\bbokeh\b": "bokeh",
            r"\bdslr\b": "digital single-lens reflex",
            r"\bmirrorless\b": "mirrorless camera",
            r"\bvfx\b": "visual effects",
            r"\bsfx\b": "special effects",
            r"\bcgi\b": "computer-generated imagery",
            r"\b3d\b": "three-dimensional",
            r"\b2d\b": "two-dimensional",
            r"\banimation\b": "animation",
            r"\bmotion graphics\b": "motion graphics",
            r"\bcompositing\b": "compositing",
            r"\brotoscoping\b": "rotoscoping",
            r"\bchroma key\b": "chroma key",
            r"\bgreen screen\b": "green screen",
            r"\bballoon\b": "blue screen",
            r"\btracking shot\b": "tracking shot",
            r"\bpanning\b": "panning",
            r"\btilting\b": "tilting",
            r"\bdolly shot\b": "dolly shot",
            r"\bcrane shot\b": "crane shot",
            r"\bsteadicam\b": "steadicam",
            r"\bagronomy\b": "agronomy",
            r"\bhorticulture\b": "horticulture",
            r"\bpomology\b": "pomology",
            r"\bclericulture\b": "olericulture",
            r"\bfloriculture\b": "floriculture",
            r"\barboriculture\b": "arboriculture",
            r"\bviticulture\b": "viticulture",
            r"\benology\b": "enology",
            r"\bsoil science\b": "soil science",
            r"\bpedology\b": "pedology",
            r"\bedaphology\b": "edaphology",
            r"\bagrochemistry\b": "agrochemistry",
            r"\bagroecology\b": "agroecology",
            r"\bsilviculture\b": "silviculture",
            r"\bagroforestry\b": "agroforestry",
            r"\bsilvopasture\b": "silvopasture",
            r"\balley cropping\b": "alley cropping",
            r"\bpermaculture\b": "permaculture",
            r"\bbiodynamic\b": "biodynamic agriculture",
            r"\bipm\b": "integrated pest management",
            r"\bgmo\b": "genetically modified organism",
            r"\bnon-gmo\b": "non-genetically modified organism",
            r"\borganic certification\b": "organic certification",
            r"\busda organic\b": "usda organic",
            r"\beu organic\b": "european union organic",
            r"\bfair trade\b": "fair trade",
            r"\braindforest alliance\b": "rainforest alliance",
            r"\butz certified\b": "utz certified",
            r"\bglobalgap\b": "global good agricultural practices",
            r"\bprecision agriculture\b": "precision agriculture",
            r"\bvrt\b": "variable rate technology",
            r"\bgps agriculture\b": "gps agriculture",
            r"\bgis agriculture\b": "gis agriculture",
            r"\byield monitoring\b": "yield monitoring",
            r"\bsoil mapping\b": "soil mapping",
            r"\bremote sensing agriculture\b": "remote sensing agriculture",
            r"\bdrone agriculture\b": "drone agriculture",
            r"\buav agriculture\b": "unmanned aerial vehicle agriculture",
            r"\bfood tech\b": "food technology",
            r"\bfood sci\b": "food science",
            r"\bfood eng\b": "food engineering",
            r"\bfood chem\b": "food chemistry",
            r"\bfood micro\b": "food microbiology",
            r"\bfood safety\b": "food safety",
            r"\bhar\b": "hazard analysis",
            r"\bccp\b": "critical control point",
            r"\bprp\b": "prerequisite program",
            r"\boprp\b": "operational prerequisite program",
            r"\bfsma\b": "food safety modernization act",
            r"\biso 22000\b": "food safety management system",
            r"\bbrcgs\b": "british retail consortium global standard",
            r"\bif food\b": "international featured standards",
            r"\bsqf\b": "safe quality food",
            r"\bmap\b": "modified atmosphere packaging",
            r"\bcAP\b": "controlled atmosphere packaging",
            r"\bvap\b": "vacuum packaging",
            r"\bvp\b": "vacuum packaging",
            r"\bretort\b": "retort processing",
            r"\basaptic\b": "aseptic processing",
            r"\bhtst\b": "high temperature short time",
            r"\buht\b": "ultra-high temperature",
            r"\bph\b": "potential of hydrogen",
            r"\baw\b": "water activity",
            r"\bmc\b": "moisture content",
            r"\btss\b": "total soluble solids",
            r"\bbrix\b": "brix",
            r"\bgluten-free\b": "gluten-free",
            r"\blactose-free\b": "lactose-free",
            r"\bnut-free\b": "nut-free",
            r"\bsoy-free\b": "soy-free",
            r"\begg-free\b": "egg-free",
            r"\bdairy-free\b": "dairy-free",
            r"\bvegan\b": "vegan",
            r"\bvegetarian\b": "vegetarian",
            r"\bkosher\b": "kosher",
            r"\bhalal\b": "halal",
            r"\bchef\b": "chef",
            r"\bexecutive chef\b": "executive chef",
            r"\bsous chef\b": "sous chef",
            r"\bchef de partie\b": "chef de partie",
            r"\bcommis chef\b": "commis chef",
            r"\bgarde manger\b": "garde manger",
            r"\bpoissonier\b": "poissonier",
            r"\brotisseur\b": "rotisseur",
            r"\bgrillardin\b": "grillardin",
            r"\bfriturier\b": "friturier",
            r"\bentremetier\b": "entremetier",
            r"\btournant\b": "tournant",
            r"\bpatissier\b": "patissier",
            r"\bboulanger\b": "boulanger",
            r"\bconfiseur\b": "confiseur",
            r"\bglacier\b": "glacier",
            r"\bdecorateur\b": "decorateur",
            r"\bcuisinier\b": "cuisinier",
            r"\baboyeur\b": "aboyeur",
            r"\bcommunard\b": "communard",
            r"\bplongeur\b": "plongeur",
            r"\bmarmiton\b": "marmiton",
            r"\bmother sauces\b": "mother sauces",
            r"\bbéchamel\b": "béchamel",
            r"\bvelouté\b": "velouté",
            r"\bespagnole\b": "espagnole",
            r"\btomate\b": "tomate",
            r"\bhollandaise\b": "hollandaise",
            r"\bmayonnaise\b": "mayonnaise",
            r"\bvinagrette\b": "vinagrette",
            r"\bbouillon\b": "bouillon",
            r"\bconsommé\b": "consommé",
            r"\bbisque\b": "bisque",
            r"\bvelouté soup\b": "velouté soup",
            r"\bpurée soup\b": "purée soup",
            r"\bchowder\b": "chowder",
            r"\bgazpacho\b": "gazpacho",
            r"\bvichyssoise\b": "vichyssoise",
            r"\bcharcuterie\b": "charcuterie",
            r"\bpâté\b": "pâté",
            r"\bterrine\b": "terrine",
            r"\brillettes\b": "rillettes",
            r"\bconfit\b": "confit",
            r"\bgalantine\b": "galantine",
            r"\bfromage\b": "fromage",
            r"\baffinage\b": "affinage",
            r"\bcrudités\b": "crudités",
            r"\bcanapé\b": "canapé",
            r"\bhors d'oeuvre\b": "hors d'oeuvre",
            r"\bentrée\b": "entrée",
            r"\bplat principal\b": "plat principal",
            r"\bbavarois\b": "bavarois",
            r"\bcrème brûlée\b": "crème brûlée",
            r"\bmousse\b": "mousse",
            r"\bsoufflé\b": "soufflé",
            r"\bpanna cotta\b": "panna cotta",
            r"\btiramisu\b": "tiramisu"   
    }
    

    for pattern, replacement in replacements.items():
        text = re.sub(pattern, replacement, text)

    # Remove extra spaces
    text = re.sub(r"\s+", " ", text).strip()

    return text

def extract_skills(text):
    text_lower = normalize_text(text)
    doc = nlp(text_lower)

    categorized_skills = {}

    matcher = PhraseMatcher(nlp.vocab)

    for category, skills in SKILLS_DB.items():
        patterns = [nlp.make_doc(skill) for skill in skills]
        matcher.add(category, patterns)

    matches = matcher(doc)

    found_skills = {}

    for match_id, start, end in matches:
        category = nlp.vocab.strings[match_id]
        skill = doc[start:end].text

        if category not in found_skills:
            found_skills[category] = set()

        found_skills[category].add(skill)

    for category, skills in found_skills.items():
        categorized_skills[category] = sorted(list(skills))

    return categorized_skills

