# Generated by Django 5.2.11 on 2026-03-09 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0003_resume_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='candidate_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
